version: '3.8'

services:
  luxd:
    image: ghcr.io/luxfi/node:genesis
    container_name: luxd-mainnet-prod
    restart: unless-stopped
    ports:
      - "9630:9630"
      - "9631:9631"
    environment:
      - LUX_IMPORTED_BLOCK_ID=646572b42a6210ac8efea0ab0df2a028acde2297c3ae07bc8dd1fc3e120b802a
      - LUX_IMPORTED_HEIGHT=1082780
      - LUX_IMPORTED_TIMESTAMP=1717148410
    volumes:
      - ./runtime/luxd-final/db:/data/db
      - ./runtime/luxd-final/configs:/data/configs
    command: [
      "--network-id=96369",
      "--db-dir=/data/db",
      "--chain-config-dir=/data/configs",
      "--http-host=0.0.0.0",
      "--http-port=9630",
      "--staking-port=9631",
      "--log-level=info",
      "--api-admin-enabled=true",
      "--api-metrics-enabled=true",
      "--bootstrap-ips=",
      "--bootstrap-ids=",
      "--dev"
    ]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9630/ext/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"